services:
  aiterminal_chat_frontend:
    build:
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: aiterminal_chat_frontend
    image: mdmourao7/martim-repo:aiterminal_chat_frontend
