name: Lint
on:
  push:
    branches:
      - main
jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"
      - name: Navigate to backend directory
        run: cd backend
      - name: Install dependencies
        run: npm ci
        working-directory: ./backend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./backend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"
      - name: Navigate to frontend directory
        run: cd frontend
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend
